### ISSUE TITLE
Ticon blank patterns disabled?

### ISSUE THREAD

**Issue by Delerium** [Hypovolemia/hypovolemia#41]
Since I jumped forward from 0.6 to the github version, I just noticed that the ticon blank patterns were disabled.  Basically that removes about 90% of the ticon mod since you can't make any tool/weapon part pattens. If the only thing left being used is oreberries, then why not just use magic crops for metals and remove ticon altogether?

Don't strip too much from the mods though.  It's starting to feel like nearly every single tool, weapon and armor is getting disabled.

**Comment by drz2k** [comment]
Nah. This is just a preparation to shift them over to foundry ;)

**Comment by Delerium** [comment]
sweet! I love how foundry does things. it's smooth.

**Comment by drz2k** [comment]
I wonder ... custom recipes for the molds (alot of work and uninteresting mechanic).

Giving out/crafting some of the items so player makes mold himself ... or even have some kind of "circle" involving the altar again... humm

**Comment by frogman79** [comment]
With so many bones around early, natural thought is to just get wood and progress into tinkers tools, crash landing drilled that into my head. :) 

I'd be down for a custom recipe for the patterns, even if I had to run a broken pattern through the altar for a few 100 lp to repair it. Maybe 2 skulls and 2 bones gets 4 patterns then maybe run that through the altar if you want to keep it involved?

**Comment by Nezraddin** [comment]
Phew, tough one.
I would say the circle in the blood altar would make it easiest to "tier" the patterns. 
Like such a tier system:
- Tier 1 Blood Altar -> Use vanilla tools!
- Tier 2 Blood Altar -> first very basic patterns (to make a pickaxe, axe, shovel)
- Tier 3 Blood Altar -> first advanced patterns (to make a lumber axe, sword, bow, hammer)
- Tier 4 Blood Altar -> very advanced patterns (crossbow, cleaver)
- Tier 5 Blood Altar -> Anything you aboslutely don't want players to have early one. Like the pattern for the scimitar.

So it would be several smaller circles, so people will advance with every upgrade they make to the blood altar. Sure there are many people who will "skip" most things (I myself only worked with lumberaxe and vanilla tools and my blood altar is tier 4 now). But I think it would fit into the "Advance thanks to blood magic"-setting.
The Cleaver should of course be in the first 4 tiers, since for tier 5 you need to fight the wither and getting the skulls for that the vanilla way... is horrible *nods seriously* ^^

It would be best to give out normal Patterns (not the items to make some with gold/aluminium brass) since there are many items where you need the normal patterns with (like the obsidian plate, for the reinforced modifier or slime parts for making your tools better and such stuff)

**Comment by Delerium** [comment]
This may be double the amount of recipes but it might be a cool mechanic.  What about putting in shaped recipes with sticks and planks to craft a "positive" mold, then using Nezraddin's method, a "negative" wooden mold can be created from the altar (can you rename them to blood molds? lol).  Just be sure that the end result is a usable *Wooden* pattern, otherwise there's no way to build parts out of non-metals.  From there to the foundry, the usual method of making cobblestone parts and using them to create metal casts would work.

Also, don't forget that with blank patterns disabled, while we may not need a stencil table, we still need alternate starter recipes for the tool station (or skip to the tool forge) and part builder so we can assemble tools and upgrade them.

**Comment by AlphaRue** [comment]
could use iguana tweaks and restrict materials so you can only make the patterns and wood tools, and set wood tinkers tools to mine speed and damage of 0, allowing us to make everything using casts in foundry blocks

**Comment by Delerium** [comment]
That wouldn't work, because not all parts are metals and can be casted.  Think about things like fletching, bowstrings, slime handles, obsidian binding, etc.  You don't want to make the non-metal parts uncraftable because that would take away alot of the good parts in ticon.

**Comment by AlphaRue** [comment]
quadrum, add custom fluids

**Comment by drz2k** [comment]
Great input guys, ill need to play around with whats possible :)

**Comment by AlphaRue** [comment]
add custom recipes for those things, and obsidian bindings can be casted

**Comment by drz2k** [comment]
Closing and referincing.
